### ISSUE TITLE
illegal instruction (core dumped)

### ISSUE THREAD

**Issue by gosha1128** [creafz/pytorch-cnn-finetune#12]
It seems that the default res-net works.  Any model that needs to be downloaded (vgg, alexnet) cause this exception.  Some examples below:

~/pytorch-cnn-finetune/examples$ python cifar10.py --model-name vgg19
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /home/ubuntu/.torch/models/vgg19-dcbb9e9d.pth
100%|‚574673361/574673361 [00:20<00:00, 28293664.65it/s]
Illegal instruction (core dumped)

~/pytorch-cnn-finetune/examples$ python cifar10.py --model-name vgg16
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /home/ubuntu/.torch/models/vgg16-397923af.pth
100%|553433881/553433881 [00:05<00:00, 98388620.83it/s]
Illegal instruction (core dumped)

**Comment by creafz** [comment]
I was not able to reproduce this issue under the latest version of pytorch-cnn-finetune, PyTorch 1.0, Ubuntu 18.04 and CUDA 10.

Could you please provide some additional info, so I can try to reproduce the issue:
1. Operating system.
2. PyTorch, torchvision, pretrainedmodels and pytorch-cnn-finetune versions (could be obtained by running `pip freeze | grep 'torch\|pretrainedmodels\|cnn-finetune'`)
3. CUDA and cuDNN versions (on Ubuntu you can use those commands to obtain version numbers: `cat /usr/local/cuda/version.txt` for CUDA and `cat /usr/include/cudnn.h | grep CUDNN_M` for cuDNN)

I have also made some changes to the library, could you try to use the latest version 0.5.3? (there were some minor compatibility changes).

**Comment by creafz** [comment]
Closed for inactivity. Please open a new issue if the error still persists.
