### ISSUE TITLE
Access to fc layer

### ISSUE THREAD

**Issue by morawi** [creafz/pytorch-cnn-finetune#13]
I need to access the fc layer in the ResNet model. With the standard ResNet, this is done using
`model.fc.weight`
However, with the ones from this repo, I am getting this error:

  ```
In [33]: model.fc.weight

raceback (most recent call last):


File "<ipython-input-33-ca343f58d0f7>", line 1, in <module>
    model.fc

  File "//anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))

AttributeError: 'ResNetWrapper' object has no attribute 'fc'

```

Is there a way around this?

**Comment by creafz** [comment]
Weights of the fully-connected layer should be accessible through `model._classifier.weight`.
