### ISSUE TITLE
mean and std used in the transform of the Cifar10 example

### ISSUE THREAD

**Issue by morawi** [creafz/pytorch-cnn-finetune#2]
In the Cifar10 example, the transform uses the mean and std of the original pre-trained (on ImageNet) model(s) ; how would this transform affect the learning from new data? Shouldn't the mean and std obtained from the new data (Cifar10 in the example)?

 ```
transform = transforms.Compose([
        transforms.ToTensor(),       
        transforms.Normalize(
            mean=model.original_model_info.mean,
            std=model.original_model_info.std),
    ])
```

**Comment by creafz** [comment]
From my experience, if a dataset has a similar distribution to ImageNet or if a dataset is small then using ImageNet preprocessing works fine and sometimes (in a case of a small dataset) even better than dataset specific preprocessing. I think the best way is to test both options on your data and see which one performs better.

As for the code in the Cifar10 example, it is used to show how one can use the library and its features such as accessing information about preprocessing used for the original model, so it uses ImageNet mean and std.
