### ISSUE TITLE
Do the parameters in the loaded pretrained-model update according to the Grad?

### ISSUE THREAD

**Issue by MSoulPlayer** [creafz/pytorch-cnn-finetune#6]
When using a custom classifier like the one in your guide:

<p>
import torch.nn as nn

def make_classifier(in_features, num_classes):
    return nn.Sequential(
        nn.Linear(in_features, 4096),
        nn.ReLU(inplace=True),
        nn.Linear(4096, num_classes),
    )

model = make_model('vgg16', num_classes=10, pretrained=True, input_size=(256, 256), classifier_factory=make_classifier)

</p>

I wonder if the parameters in the pretrained-model update or it just trains a custom classifier on top of the net?
if I only want to train a custom classifier on top of the net, what should I do?
Much Thanks.

**Comment by creafz** [comment]
By default, all parameters of a model will be updated during training process. If you want  to train only classifier, you could 'freeze' feature extracting layers by setting `requires_grad=False`:

```
for param in model._features.parameters():
    param.requires_grad = False

# Print layers whose parameters will be updated during training.
# Should print only names of classifying layers.
print([name for (name, param) in model.named_parameters() if param.requires_grad])
```


You will also need to pass only parameters from 'unfrozen' layers to an optimizer or you will get an exception

```
optimizer = optim.SGD((param for param in model.parameters() if param.requires_grad), lr=..., momentum=...)
```

**Comment by liweizhong666** [comment]
for param in model._features.parameters():
    param.requires_grad = False

where should this code be setted?

**Comment by liweizhong666** [comment]
Can I freeze only a few layers in the pre-training weights? How to set it up? Thank you
