### ISSUE TITLE
Finetune on multi-GPUs

### ISSUE THREAD

**Issue by Ken2yLiu** [creafz/pytorch-cnn-finetune#7]
I want to finetune the models on multi-GPUs, as following the office documents, I try this:
`model = make_model(
    args.model_name,
    pretrained=True,
    num_classes=len(classes),
    dropout_p=args.dropout_p,
    use_original_classifier=True
)`
`model = nn.DataParallel(model)`
`model = model.to(device)`

But get error as:
`Traceback (most recent call last):
  File "pg_cls.py", line 83, in <module>
    mean=model.original_model_info.mean,
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'original_model_info'`

**Comment by creafz** [comment]
I assume you are using code from https://github.com/creafz/pytorch-cnn-finetune/blob/master/examples/cifar10.py, am I correct?

I have made a modified version of this code that should work with nn.DataParallel, could you try it? - https://gist.github.com/creafz/89240e45993d009cfa505eb9057ccc9d

In comparison with the original cifar10.py, I have changed lines (59-61) https://gist.github.com/creafz/89240e45993d009cfa505eb9057ccc9d#file-cifar10-py-L59-L61 and lines  (68-69) https://gist.github.com/creafz/89240e45993d009cfa505eb9057ccc9d#file-cifar10-py-L68-L69

I think the problem with the original example is that `transforms.Normalize` expects that it will receive the original model that will have an `original_model_info` attribute. But when nn.DataParallel is used the original model wrapped into a nn.DataParallel object which doesn't have this attribute. So as a workaround the updated version of the example saves `model.original_model_info.mean` and `model.original_model_info.std` into standalone variables before the model is wrapped into nn.DataParallel and later those variables are used in the `transforms.Normalize` call.

**Comment by Ken2yLiu** [comment]
Yes, the problem is exactly what you said, and your modified code fixes that.

I am finetuning using multi-GPU now. It's much faster!

Thanks!

Further more, are you considering to add more functions in this repo, like what if I want to fix some pre layers but only finetune the last two layers?

**Comment by John1231983** [comment]
Good job. I have a question. If I want to train only FC layer in first five epoch with pre-trained model, then from sixth epoch, I will fine-tuning (train all layer), How should I do? Can I add it in train function of cifar
https://github.com/creafz/pytorch-cnn-finetune/blob/542b84c545d95345a2d421e3b682872e5a845c9e/examples/cifar10.py#L89

```
 model.train()
    if epoch >= 5:
        for param in model.parameters():
            param.requires_grad = True
    for batch_idx, (data, target) in enumerate(train_loader):
   
```

**Comment by creafz** [comment]
@John1231983 You need to initialize an optimizer after  `requires_grad` attributes are set for each param, so the optimizer will know which parameters it should update and which it shouldn't.

Also, note that code like `optimizer = optim.Adam(...)` will create a new optimizer instance, so you will lose the previous optimizer state (an Adam optimizer, for example, maintains exponential moving averages of gradient and its square and use them to update weights of a neural network).

I think this code should work however I haven't thoroughly tested it:
1. Replace https://github.com/creafz/pytorch-cnn-finetune/blob/542b84c545d95345a2d421e3b682872e5a845c9e/examples/cifar10.py#L123-L125 with:

```
for param in model._features.parameters():
    param.requires_grad = False
optimizer = optim.Adam((param for param in model.parameters() if param.requires_grad), lr=args.lr, weight_decay=0.0001)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.1)

# We start epochs counting from 1
for epoch in range(1, args.epochs + 1):
    if epoch == 6:
        for param in model._features.parameters():
            param.requires_grad = True
        # Add unfrozen parameters to the optimizer so it will update them.
        optimizer.add_param_group({'params': list(model._features.parameters())})
    
    # Pass the optimizer to the train function
    train(optimizer, epoch)
    test()
    scheduler.step(epoch)
```

2. Update the `train` function so it will receive an optimizer instance as an argument, replace https://github.com/creafz/pytorch-cnn-finetune/blob/542b84c545d95345a2d421e3b682872e5a845c9e/examples/cifar10.py#L86 with:

`def train(optimizer, epoch):`

**Comment by John1231983** [comment]
Very clear. Thanks. I think you can provide some example like this question because it is a trick to use pretrain ( we did not finetune all network at the first epoch)

**Comment by Ken2yLiu** [comment]
@creafz sorry for replying late, your answers help a lot, then I would close this issue now
