### ISSUE TITLE
How to replace last FC layer by 1x1 convolution?

### ISSUE THREAD

**Issue by John1231983** [creafz/pytorch-cnn-finetune#9]
Thanks for sharing a great API. I want to perform FCN (Fully convolutional network for semantic segmentation) using your API. It can be done by replacing the last Fully connected layer by 1x1 convolutional layer. Let's take resnet-18 as an example, how could I modify it to perform semantic segmentation. I think your classification example is good, and if you make an example for segmentation then it will be very good.

**Comment by creafz** [comment]
An example function that creates a classifier with a 1x1 convolution layer:

```
def make_fcn_classifier(in_features, num_classes):
    return nn.Conv2d(in_channels=in_features, out_channels=num_classes, kernel_size=1)
```

After that a model can be created with the following code:

```
model = make_model('resnet18', num_classes=3, pretrained=True, classifier_factory=make_fcn_classifier, pool=None)

# Do not flatten the output of a feature extractor
model.flatten_features_output = False
```


Note however that a feature extractor from resnet18 will output a downsampled image activation map (7x7 pixels), so you may want to add some upsampling layers before a 1x1 convolution, something like this:

```
def make_fcn_classifier(in_features, num_classes):
    return nn.Sequential(
        # This block with 4 layers can be repeated multiple times to upsample the input further.        
        nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True),
        # Generally speaking, for each upsamling operation you also need to reduce the number of features
        # to decrease memory footprint of a neural network. So `out_channels=in_features // 2` is used
        # for nn.Conv2d
        nn.Conv2d(in_channels=in_features, out_channels=in_features // 2, kernel_size=3),
        nn.BatchNorm2d(in_features // 2),
        nn.ReLU(inplace=True),

        nn.Conv2d(in_channels=in_features // 2, out_channels=num_classes, kernel_size=1)
    )
```

I also recommend you to take a look at https://github.com/ternaus/TernausNet which was made exactly for semantic segmentation tasks.

**Comment by John1231983** [comment]
Thanks. I got it.

I have one more question that is how can we get intermediate feature and up-sampling them. For example, FCN-8s, they upsampling the intermediate features (from coarse to fine) and fusion to get better performance. Normally, we can do it by rewriting the model and modify it in forwarding function. But I am not sure if we have a better way using your API. Thanks

**Comment by creafz** [comment]
This feature is not supported and I am not planning to add it to the library, because it requires a lot of internal changes. Also, I think that TernausNet is much better suited for this kind of tasks.
